-- TEXT DATA TYPE
-- CHAR  = 1 
-- CHAR (N)  FIXED LENGTH RETURN BLANK 
-- VARCHAR VARYING LENGTH
-- TEXT VARYING LENGTH UNLIMITED

-- SELECT '01234'::CHAR(3) -- 3 REMIAIN OTHER TRUNCATE


-- SELECT T.C::CHAR(10)
-- FROM
-- (VALUES('01234'),('0123456789')) AS T(C)

-- "01234     "


-- SELECT T.C, 
-- LENGTH(T.C) AS CHARS
-- , OCTET_LENGTH(T.C) AS BYTES
-- FROM 
-- (VALUES('X'),
-- ('Ὰ'),
-- ('🦽🚍')) AS T(C);


--NUMERIC 
--<PRECISION>,<SCALE>


-- SELECT (2::NUMERIC)^100000


EXPLAIN ANALYZE 

-- WITH ONE_MILLION_ROWS(X) AS (
-- SELECT T.X::NUMERIC(8,0)
-- 	FROM GENERATE_SERIES(0,1000000) AS T(X)
-- )

-- SELECT T.X + T.X AS ADD
-- FROM ONE_MILLION_ROWS AS T;


-- EXPLAIN ANALYZE 

-- WITH ONE_MILLION_ROWS(X) AS (
-- SELECT T.X::INT
-- 	FROM GENERATE_SERIES(0,1000000) AS T(X)
-- )

-- SELECT T.X + T.X AS ADD
-- FROM ONE_MILLION_ROWS AS T


--TUPPER FORMULA