-- UNION ALL BAG UNION 
-- INTERSECT ALL BAG INTERSECTION
-- EXCEPT ALL BAG DIFFERENCE 
-- WITHOUT ALL NO DUPLICATE
-- ROW WIDTH AND TYPE MUST MATCH

-- SELECT T.*
-- FROM T AS T
-- WHERE T.C

-- UNION ALL

-- SELECT T.*
-- FROM T AS T 
-- WHERE NOT T.C


-- SELECT T.*
-- FROM T AS T
-- WHERE T.C

-- UNION 

-- SELECT T.*
-- FROM T AS T 
-- WHERE NOT T.C



-- SELECT T.B
-- FROM T AS T
-- WHERE T.C

-- UNION All

-- SELECT T.B
-- FROM T AS T 
-- WHERE NOT T.C

-- SELECT T.B
-- FROM T AS T
-- WHERE T.C

-- UNION 

-- SELECT T.B
-- FROM T AS T 
-- WHERE NOT T.C


-- SELECT 1 AS Q , T.B
-- FROM T AS T
-- WHERE T.C

-- UNION All

-- SELECT 2 AS Q, T.B
-- FROM T AS T 
-- WHERE NOT T.C


-- SELECT  T.B
-- FROM T AS T
-- WHERE T.C

-- EXCEPT All

-- SELECT  T.B
-- FROM T AS T 
-- WHERE NOT T.C


-- SELECT  T.B
-- FROM T AS T 
-- WHERE NOT T.C
-- EXCEPT All

-- SELECT  T.B
-- FROM T AS T
-- WHERE T.C

-- MULTI-DIMENSIONAL DATA


-- DROP TABLE IF EXISTS PREHISTORIC;

-- CREATE TABLE PREHISTORIC(
-- CLASS TEXT, 
-- 	HERBIVORE BOOLEAN, 
-- 	LEGS INT, 
-- 	SPECIES TEXT
-- )

-- INSERT INTO PREHISTORIC VALUES ('MAMMALIA', TRUE, 2, 'MEGATHERIUM'),
-- ('MAMMALIA', TRUE, 4, 'PARACERATHERIUM'),
-- ('MAMMALIA', FALSE, 2, NULL),
-- ('MAMMALIA', FALSE, 4, 'SABRETOOTH'),
-- ('REPTILLIA', TRUE, 2, 'IGUAMPDON'),
-- ('REPTILLIA', TRUE, 4, 'BARCHIOSAURUS'),
-- ('REPTILLIA', FALSE, 2, 'VELOCIRAPTOR'),
-- ('REPTILLIA', FALSE, 4, NULL);

-- MULTIPLE GROUP BYS: GROUPING SETS

--TABLE PREHISTORIC

-- SELECT 
-- P.CLASS, 
-- P.HERBIVORE, 
-- P.LEGS,
-- STRING_AGG(P.SPECIES, ', ') AS SPECIES
-- FROM PREHISTORIC AS P
-- GROUP BY GROUPING SETS((CLASS),(HERBIVORE), (LEGS))


-- SELECT 
-- P.CLASS, 
-- NULL :: BOOLEAN AS "HERBIVORE?", 
-- NULL :: INT AS LEGS,
-- STRING_AGG(P.SPECIES, ', ') AS SPECIES
-- FROM PREHISTORIC AS P
-- GROUP BY P.CLASS

-- UNION ALL 

-- SELECT 
-- NULL:: TEXT AS CLASS, 
-- P.HERBIVORE AS "HERBIVORE?", 
-- NULL :: INT AS LEGS,
-- STRING_AGG(P.SPECIES, ', ') AS SPECIES
-- FROM PREHISTORIC AS P
-- GROUP BY P.HERBIVORE

-- UNION ALL 

-- SELECT 
-- NULL:: TEXT AS CLASS, 
-- NULL :: BOOLEAN AS "HERBIVORE?", 
-- P.LEGS AS LEGS,
-- STRING_AGG(P.SPECIES, ', ') AS SPECIES
-- FROM PREHISTORIC AS P
-- GROUP BY P.LEGS



-- ROLL UP - GROUP AALONG THE PATH

-- SELECT 
-- P.CLASS, 
-- P.HERBIVORE,
-- P.LEGS,
-- STRING_AGG(P.SPECIES, ',') AS  SPECIES
-- FROM PREHISTORIC AS P 
-- GROUP BY ROLLUP(CLASS, HERBIVORE, LEGS)
-- SELECT 

-- STRING_AGG(P.SPECIES, ',') AS  SPECIES
-- FROM PREHISTORIC AS P 
-- GROUP BY ();

-- CUBE
 -- ALL SUBSET WITH 2^N ARE CONSIDER



SELECT 
P.CLASS, 
P.HERBIVORE,
P.LEGS,
STRING_AGG(P.SPECIES, ',') AS  SPECIES
FROM PREHISTORIC AS P 
GROUP BY CUBE(CLASS, HERBIVORE, LEGS)

-- 2 ^ 3 = 8 

-- 1. FROM 
-- 2. WHERE
-- 3. COLUMNS AGGREGATION
-- 4. GROUP BY 
-- 5. HAVING 

-- 6.UNION/EXCEPT/INTERSECT

-- 7. ORDER BY 
-- 8. OFFSET 
-- 9. LIMIT

-- QUERY NESTING AND NON READABILITY

-- WITH 
-- COMMON TABLE EXPRESSION - BUNDLE A QUERY WITH TEST DATA

WITH 
PREHISTORIC(CLASS,HERBIVORE, LEGS, SPECIES)AS 
	VALUES('MAMMALIA', TRUE, 2, 'MEGATHERIUM')





