-- TIMESTAMP AND TIME INTERVALS
-- T2-T1 INTERVAL
-- TIMESTAMP/TIME/INTERVAL
-- NOW() -SYSTEM TIME

-- SELECT 'NOW':: DATE , 
-- 	'NOW':: TIME, 
-- 	'NOW':: TIMESTAMP

-- WITH TIMEZONE
-- SELECT 'NOW' :: TIMESTAMP ,
-- 		'NOW':: TIMESTAMP WITH TIME ZONE

--SET DATESTYLE = 'GERMAN, MDY'
-- SELECT '5-4-2022' :: DATE

-- SET DATESTYLE = 'ISO,MDY'

-- SELECT  COUNT(DISTINCT BIRTHDAY.D::DATE) AS INTERPRETATION
-- FROM (VALUES('AUGUST 26, 1968'),('AUG 26, 1968')) AS BIRTHDAY (D)


SELECT 'EPOCH':: TIMESTAMP, 
'TODAY':: TIMESTAMP,
'TOMORROW':: TIMESTAMP,
'INFINITY'::TIMESTAMP,
'YESTERDAY'::TIMESTAMP,
TIMEOFDAY(),
'NOW'::TIMESTAMP - 'YESTERDAY'::TIMESTAMP,
'TOMORROW'::TIMESTAMP - NOW(),
'AUG 31, 2035'::DATE - NOW()


-- ;WITH t AS
-- (
--     SELECT v2.n * 10 + v1.n AS N
--     FROM (VALUES (0), (1), (2), (3), (4), (5), (6), (7), (8), (9)) v1(n)
--     CROSS JOIN (VALUES (0), (1), (2), (3), (4), (5), (6), (7), (8), (9)) v2(n)
-- )
-- SELECT T.N
-- FROM t
-- ORDER BY T.n;
